<div>
    <div>
        <h4>Auditoriums</h4>
        <ul>
            <li><a href=<?php echo HOST . '/auditoriums'; ?>>Back</a></li>
            <li><a href=<?php echo HOST ; ?>>Main menu</a></li>
        </ul>

        <div>
            <table border="1">
                <tr>
                    <td>id</td>
                    <td>Name</td>
                    <td>Number of Seats</td>
                    <td>Vip seats</td>
                </tr>
                <?php foreach ($auditoriums as $auditorium): ?>
                    <tr>
                        <td><?php echo $auditorium->getId(); ?></td>
                        <td><?php echo $auditorium->getName(); ?></td>
                        <td><?php echo $auditorium->getSeatsNumber(); ?></td>
                        <td><?php echo $auditorium->getVipSeats(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
