<div>
    <div>
        <p>Main Menu</p>
        <ul>
            <li><a href="/">Back</a></li>
        </ul>

        <div>
            <form method="post">
                <label for="aud_name">Enter Auditorium name</label>
                <input type="text" name="aud_name"/>
                <input type="submit"/>
            </form>
        </div>

        <br />

        <?php if (count($data)): ?>
            <div>
                <table border="1">
                    <tr>
                        <td>id</td>
                        <td>Name</td>
                        <td>Number of Seats</td>
                        <td>Vip seats</td>
                    </tr>
                    <tr>
                        <td><?php echo $auditorium->getId(); ?></td>
                        <td><?php echo $auditorium->getName(); ?></td>
                        <td><?php echo $auditorium->getSeatsNumber(); ?></td>
                        <td><?php echo $auditorium->getVipSeats(); ?></td>
                    </tr>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>
