<div>
    <div>
        <h4>Manage Users</h4>
        <ul>
            <li><a href=<?php echo HOST. '/users';?>>Back</a></li>
            <li><a href=<?php echo HOST ; ?>>MAin Menu</a></li>
        </ul>

        <div>
            <form method="post">
                <table>
                    <tr>
                        <td><label for="first_name">First name</label></td>
                        <td><input type="text" name="first_name"/></td>
                    </tr>
                    <tr>
                        <td><label for="last_name">Last name</label></td>
                        <td><input type="text" name="last_name"/></td>
                    </tr>
                    <tr>
                        <td><label for="email">Email</label></td>
                        <td><input type="text" name="email"/></td>
                    </tr>
                    <tr>
                        <td><label for="birthday">Birthday (yyyy-mm-dd)</label></td>
                        <td><input type="text" name="birthday"/></td>
                    </tr>
                </table>
                <input type="submit" value="Добавить пользователя" />
            </form>
        </div>
    </div>
</div>
