<div>
    <p style="font-size: 24px;">Welcome to the Cinema</p>
    <div>
        <p>Main Menu</p>
        <ul>
            <li><a href=<?php echo HOST . '/users/add'; ?>>Add user</a></li>
            <li><a href=<?php echo HOST . '/users/all'; ?>>View all users</a></li>
            <li><a href=<?php echo HOST . '/users/findById'; ?>>Find user by id</a></li>
            <li><a href=<?php echo HOST . '/users/findByEmail'; ?>>Find user by email</a></li>
            <li><a href=<?php echo HOST;?>>Back</a></li>
        </ul>
    </div>
</div>
