<div>
    <p style="font-size: 24px;">Welcome to the Cinema</p>
    <div>
        <p>Main Menu</p>
        <ul>
            <li><a href="/users/add">Add user</a></li>
            <li><a href="/users/all">View all users</a></li>
            <li><a href="/users/findById">Find user by id</a></li>
            <li><a href="/users/findByEmail">Find user by email</a></li>
            <li><a href="/">Back</a></li>
        </ul>
    </div>
</div>
