<div>
    <div>
        <p>Main Menu</p>
        <ul>
            <li><a href="/">Back</a></li>
        </ul>

        <div>
            <form method="post">
                <table>
                    <tr>
                        <td><label for="first_name">First name</label></td>
                        <td><input type="text" name="first_name"/></td>
                    </tr>
                    <tr>
                        <td><label for="last_name">Last name</label></td>
                        <td><input type="text" name="last_name"/></td>
                    </tr>
                    <tr>
                        <td><label for="email">Email</label></td>
                        <td><input type="text" name="email"/></td>
                    </tr>
                    <tr>
                        <td><label for="birthday">Birthday</label></td>
                        <td><input type="text" name="birthday"/></td>
                    </tr>
                </table>
                <input type="submit"/>
            </form>
        </div>
    </div>
</div>
