<div>
    <p style="font-size: 24px;">Welcome to the Cinema</p>
    <div>
        <p>Manage events</p>
        <ul>
            <li><a href=<?php echo HOST . '/events/add'; ?>>Add event</a></li>
            <li><a href=<?php echo HOST . '/events/all'; ?>>View all events</a></li>
            <li><a href=<?php echo HOST . '/events/findById'; ?>>Find event by id</a></li>
            <li><a href=<?php echo HOST . '/events/findByName'; ?>>Find event by name</a></li>
            <li><a href=<?php echo HOST;?>>Back</a></li>
        </ul>
    </div>
</div>
