<div>
    <div>
        <p>Booking management</p>
        <ul>
            <li><a href=<?php echo HOST . '/tickets'; ?>>Back</a></li>
        </ul>

        <div>
            <table border="1">
                <tr>
                    <td>id</td>
                    <td>user id</td>
                    <td> event id</td>
                    <td> date time</td>
                    <td>Vip seat</td>
                </tr>
                <?php foreach ($tickets as $ticket): ?>
                    <tr>
                        <td><?php echo $ticket->getId(); ?></td>
                        <td><?php echo $ticket->getUser_id(); ?></td>
                        <td><?php echo $ticket->getEvent_id(); ?></td>
                        <td><?php echo $ticket->getDateTime(); ?></td>
                        <td><?php echo $ticket->getSeat(); ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
