<div>
    <p style="font-size: 24px;">Welcome to the Cinema</p>
    <div>
        <p>Main Menu</p>

        <ul>
            <li><a href=<?php echo HOST . '/auditoriums'; ?>>View auditoriums</a></li>
            <li><a href=<?php echo HOST . '/events'; ?>>Manage events</a></li>
            <li><a href=<?php echo HOST . '/users'; ?>>Manage users</a></li>
            <li><a href=<?php echo HOST . '/tickets'; ?>>Book tickets</a></li>
        </ul>
    </div>
</div>
